# Generated by Django 4.1.5 on 2024-02-02 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_id', models.BigIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('product_id',),
            },
        ),
        migrations.CreateModel(
            name='UserVL',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Logistics User',
                'verbose_name_plural': 'Logistics Users',
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product', models.ManyToManyField(to='logistics.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.uservl')),
            ],
            options={
                'ordering': ('order_id',),
            },
        ),
    ]
